import "./globals.css";
import { AuthContextProvider } from "../context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{
        backgroundImage: `url("imgs/bgimg.jpeg")`,
        backgroundSize: 'cover',
        
        backgroundRepeat: 'no-repeat',
        position: 'relative',
        minHeight: '100vh',
      }}>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
